### ISSUE TITLE
Logout Functionality

### ISSUE THREAD

**Issue by nikhith-beta** [mrpateljeet/Group_3_Engineers#28]
Title: As a user, I should be able to log out so I can securely end my session.

Description: Develop a logout feature to allow users to end their session securely.

Acceptance Criteria:

Users can log out from any page within the app.
Upon logging out, the user session is invalidated.
The user is redirected to the login page after logging out.
The logout button is accessible and clearly visible in the app’s UI.

**Comment by DChanakya** [comment]
Merged to main
