### ISSUE TITLE
Story 1: Set Up Development Environment

### ISSUE THREAD

**Issue by mrpateljeet** [mrpateljeet/Group_3_Engineers#3]
**Title:** As a developer, I want to set up the development environment so that the team can start coding efficiently.

**Description:** Prepare the development environment for both backend and frontend, including version control, dependencies, and initial project structure.

**Acceptance Criteria:**
Development environment is set up for backend and frontend.
Necessary dependencies are installed and configured.
Version control is set up with a GitHub repository.
Basic project structure is created.

**Comment by BollepalliPranitha** [comment]
Development environment is set up for backend and frontend.
Necessary dependencies are installed and configured.
Version control is set up with a GitHub repository.
Basic project structure is created.
